### ISSUE TITLE
gEE

### ISSUE THREAD

**Issue by evad1n** [human37/gee#14]
<pre>                                                 
                                                 
              __.....__           __.....__      
  .--./)  .-''         '.     .-''         '.    
 /.''\\  /     .-''"'-.  `.  /     .-''"'-.  `.  
| |  | |/     /________\   \/     /________\   \ 
 \`-' / |                  ||                  | 
 /("'`  \    .-------------'\    .-------------' 
 \ '---. \    '-.____...---. \    '-.____...---. 
  /'""'.\ `.             .'   `.             .'  
 ||     ||  `''-...... -'       `''-...... -'    
 \'. __//                                        
  `'---'                                         </pre>

**Comment by human37** [comment]
Very good point
